website/views.py
from flask import Flask, Blueprint, render_template, request, flash, jsonify, redirect, url_for, session
from flask_login import login_required, current_user
from .products.models import Product, Category, Brand
from . import db
from sqlalchemy.sql import func
from werkzeug.utils import secure_filename
import uuid as uuid
import os

UPLOAD_FOLDER = 'website/static/images/product_images'
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

views = Blueprint('views', __name__)
    

@views.route('/insert/newproduct', methods=['GET', 'POST'])
@login_required
def insertProd():
    if request.method == 'POST':
        name = request.form.get('name')
        desc = request.form.get('description')
        prod_image = request.files['image2']
        # if user does not select file, return to signup
        if prod_image.filename == '':
            prod_image = 'None'
        elif prod_image and not allowed_file(prod_image.filename):
            flash('Please select an image file', category="error")
            return redirect(url_for('views.insert'))
        elif prod_image and allowed_file(prod_image.filename):
            # Grab Image Name
            prod_filename = secure_filename(prod_image.filename)
            # Set UUID
            prod_name = str(uuid.uuid1()) + "_" + prod_filename
            # Save that Image
            prod_image.save(os.path.join(app.config['UPLOAD_FOLDER'], prod_name))
            # Change it to string to save to db
            prod_image = prod_name
        brand = request.form.get('brand')
        category = request.form.get('category')
        stock = request.form.get('stock')
        discount = request.form.get('discount')
        price = request.form.get('price')


        if len(name) < 1:
            flash('Product name is too short!', category='error')
        else:
            new_product = Product(name=name, description=desc, image=prod_image, brand_id=brand, category_id=category, stock=stock, discount=discount, price=price)
            db.session.add(new_product)
            db.session.commit()
            flash('Product added in Product List!', category='success')

    return redirect(url_for('auth.adminhome'))


@views.route('/insert/newcategory', methods=['GET', 'POST'])
@login_required
def insertCat():
    if request.method == 'POST':
        name = request.form.get('name')

        if len(name) < 1:
            flash('Category name is too short!', category='error')
        else:
            new_category = Category(name=name)
            db.session.add(new_category)
            db.session.commit()
            flash('A new category has been added!', category='success')

    return redirect(url_for('auth.panelCat'))


@views.route('/insert/newbrand', methods=['GET', 'POST'])
@login_required
def insertBrand():
    if request.method == 'POST':
        name = request.form.get('name')

        if len(name) < 1:
            flash('Brand name is too short!', category='error')
        else:
            new_brand = Brand(name=name)
            db.session.add(new_brand)
            db.session.commit()
            flash('A new brand has been added!', category='success')

    return redirect(url_for('auth.panelBrand'))


@views.route('/editProd', methods=['GET', 'POST'])
@login_required
def editProd():
    if request.method == 'POST':
        product = Product.query.get(request.form.get('id'))
        product.name = request.form['name']
        product.description = request.form['description']
        prod_image = request.files['image2']
        # if user does not select file, return to signup
        if prod_image.filename == '':
            product.image = product.image
        if prod_image and not allowed_file(prod_image.filename):
            flash('Please select an image file', category="error")
            return redirect(url_for('views.edit'))
        if prod_image and allowed_file(prod_image.filename):
            # Grab Image Name
            prod_filename = secure_filename(prod_image.filename)
            # Set UUID
            prod_name = str(uuid.uuid1()) + "_" + prod_filename
            if product.image == 'None':
                jsonify()
            else:
                os.unlink(os.path.join(app.config['UPLOAD_FOLDER'], product.image))
            # Save that Image
            prod_image.save(os.path.join(app.config['UPLOAD_FOLDER'], prod_name))
            # Change it to string to save to db
            product.image = prod_name
        brand = request.form['brand']
        if brand == '':
            product.brand_id = product.brand_id
        else:
            product.brand_id = brand
        category = request.form['category']
        if category == '':
            product.category_id = product.category_id
        else:
            product.category_id = category
        product.stock = request.form['stock']
        product.discount = request.form['discount']
        product.price = request.form['price']
        product.date = func.now()

        db.session.commit()
        flash('Successfully edited product in Product List!', category='success')

        return redirect(url_for('auth.adminhome'))


@views.route('/editCat', methods=['GET', 'POST'])
@login_required
def editCat():
    if request.method == 'POST':
        category = Category.query.get(request.form.get('id'))
        category.name = request.form['name']

        db.session.commit()
        flash('Successfully edited category in Category List!', category='success')

        return redirect(url_for('auth.panelCat'))


@views.route('/editBrand', methods=['GET', 'POST'])
@login_required
def editBrand():
    if request.method == 'POST':
        brand = Brand.query.get(request.form.get('id'))
        brand.name = request.form['name']

        db.session.commit()
        flash('Successfully edited brand in Brand List!', category='success')

        return redirect(url_for('auth.panelBrand'))

        

@views.route('/deleteprod/<id>/', methods=['GET', 'POST'])
@login_required
def deleteProd(id):
    product = Product.query.get(id)
    if product.image == 'None':
        jsonify()
    else:
        os.unlink(os.path.join(app.config['UPLOAD_FOLDER'], product.image))
    db.session.delete(product)
    db.session.commit()
    flash('Successfully deleted product in Product List!', category='success')

    return redirect(url_for('auth.adminhome'))


@views.route('/deletebrand/<id>/', methods=['GET', 'POST'])
@login_required
def deleteBrand(id):
    brand = Brand.query.get(id)
    db.session.delete(brand)
    db.session.commit()
    flash('Successfully deleted brand in Brand List!', category='success')

    return redirect(url_for('auth.panelBrand'))


@views.route('/deletecat/<id>/', methods=['GET', 'POST'])
@login_required
def deleteCat(id):
    category = Category.query.get(id)
    db.session.delete(category)
    db.session.commit()
    flash('Successfully deleted category in Category List!', category='success')

    return redirect(url_for('auth.panelCat'))


@views.route('/delete-allproducts', methods=['GET','POST'])
@login_required
def deleteAllProducts():
    products = Product.query.all()
    if products:
        for product in products:
            if product.image == 'None':
                jsonify()
            else:
                os.unlink(os.path.join(app.config['UPLOAD_FOLDER'], product.image))
            db.session.delete(product)
        db.session.commit()
        flash('Successfully cleared the Product List!', category='success')
    else:
        flash('Product List is empty!', category='error')

    return redirect(url_for('auth.adminhome'))


@views.route('/delete-allbrands', methods=['GET','POST'])
@login_required
def deleteAllBrands():
    brands = Brand.query.all()
    if brands:
        for brand in brands:
            db.session.delete(brand)
        db.session.commit()
        flash('Successfully cleared the Brand List!', category='success')
    else:
        flash('Brand List is empty!', category='error')

    return redirect(url_for('auth.panelBrand'))


@views.route('/delete-allcategories', methods=['GET','POST'])
@login_required
def deleteAllCategories():
    categories = Category.query.all()
    if categories:
        for category in categories:
            db.session.delete(category)
        db.session.commit()
        flash('Successfully cleared the Category List!', category='success')
    else:
        flash('Category List is empty!', category='error')

    return redirect(url_for('auth.panelCat'))

@views.route('/addCart', methods=['GET','POST'])
@login_required
def addCart():
    try:
        product_id = request.form.get('product_id')
        quantity = request.form.get('quantity')
        product = Product.query.filter_by(id=product_id).first()
        if request.method == "POST" and product_id and quantity:
            DictItems = {product_id:{"name":product.name, 'price':int(product.price), 'discount':product.discount, 'quantity':int(quantity), 
                        'image':product.image, 'stock':product.stock}}
            if 'shopcart' in session:
                print(session['shopcart'])
                if product_id in session['shopcart']:
                    for key, item in session['shopcart'].items():
                        if int(key) == int(product_id):
                            session.modified = True
                            item['quantity'] += 1
                    flash("This product is already in your Cart! Adding Quantity +1", category="error")
                else:
                    session['shopcart'] = merge_dict(session['shopcart'], DictItems)
            else:
                session['shopcart'] = DictItems
                return redirect(request.referrer)
                
    except Exception as e:
        print(e)
    finally:
        return redirect(request.referrer)


@views.route('/updateOrder/<int:code>', methods=['GET', 'POST'])
@login_required

website/templates/customers/carts.html
{% extends "base.html" %} 
{% block title %}Home - Sparkle Online Shop{% endblock %} {% block content %}
    <div class="container">
      <div class="jumbotron p-3 well text-center">
        <h1><img src="{{ url_for('static', filename='images/logos/sparkle.png') }}" id="img" x="0" y="0" height="110px" width="110px" style="border:3px solid; border-color:yellow; border-radius:55px" alt="Sparkle Logo"><br>SPARKLE ONLINE SHOP</h1>
      </div>
      <div class="jumbotron p-3">
        <h2 class="well text-center"><b>Your Shopping Cart</b></h2>
      </div>
      <div class="row bg-light">
        <table class="table table-sm">
            <thead align="center">
                <th>Sr</th>
                <th>Image</th>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Discount</th>
                <th>Subtotal</th>
                <th>Actions</th>
            </thead>
            <tbody   align="center">
                {% for key , product in session['shopcart'].items() %}
                {% set discount = "%.2f" |format((product.discount/100) * product.price|float) %}
                <tr>
                    <td>{{ loop.index }}</td>
                    {% if product.image == 'None' %}
                        <td><img data-toggle="modal" data-target="#descmodal" src="{{ url_for('static', filename='images/product_images/default-product-image.png')}}" width="50"></td>
                    {% else %}
                        <td><img data-toggle="modal" data-target="#descmodal" src="{{ url_for('static', filename='images/product_images/' + product.image)}}" width="50"></td>
                    {% endif %}
                    <td>{{ product.name }}</td>
                    <form action="{{ url_for('views.updateOrder', code=key) }}" method="POST">
                    {{ csrf_token }}
                    <td>₱ {{ product.price }}</td>
                    <td><input type="number" name="quantity" min="1" max="{{ product.stock }}" value="{{ product.quantity }}"></td>
                    {% if product.discount > 0 %}
                        <td>{{ product.discount }} % is ₱ {{ discount }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    {% set subtotal = product.quantity|int * product.price|float - discount|float %}
                    <td>₱ {{ subtotal }}</td>
                    <td>
                        <button type="submit" class="btn btn-info btn-xs">Update</button>
                    </form>
                        <a href="{{ url_for('views.removeItem', id=key) }}" class="btn btn-warning btn-xs" onclick="return confirm('Are you sure you want to remove this product from your Cart?')">Remove</a>
                    </td>
                </tr>

                
                {% endfor %}
            </tbody>
            <table class="table table-sn">
                <tr>
                    <td><a href="{{ url_for('auth.getOrder')}}" class="btn btn-primary btn-xs float-left ml-sm-5 mr-sm-5">Order Now</a></td>
                    <td><h4><b>Tax : ₱ {{ tax }}</b></h4></td>
                    <td><h4><b>Grand Total : ₱ {{ grandtotal }}</b></h4></td>
                    <td><a href="{{ url_for('views.clearCart')}}" class="btn btn-danger btn-xs float-right mr-sm-5" onclick="return confirm('Are you sure you want to clear items from your Cart?')">Clear Cart</a></td>
                </tr>
            </table>
        </table>
      </div>

    </div>

    <div class="jumbotron p-1 mt-5">
        <h4 class="well text-center">© 2022 Copyright: Sparkle Online Shop - <a href="https://www.facebook.com/profile.php?id=100089051707212&mibextid=ZbWKwL">Team Alola</a></h4>
    </div>
  

{% endblock %}

website/templates/customers/index.html
{% extends "base.html" %} 
{% block title %}Home - Sparkle Online Shop{% endblock %} {% block content %}
    <div class="container">
      <div class="jumbotron p-3 well text-center">
        <h1><img src="{{ url_for('static', filename='images/logos/sparkle.png') }}" id="img" x="0" y="0" height="110px" width="110px" style="border:3px solid; border-color:yellow; border-radius:55px" alt="Sparkle Logo"><br>SPARKLE ONLINE SHOP</h1>
      </div>
      {% if brand %}
      <div class="jumbotron p-3">
        <h2 class="well text-center"><b>Brand Products</b></h2>
      </div>
      {% elif get_catprod %}
      <div class="jumbotron p-3">
        <h2 class="well text-center"><b>Category Products</b></h2>
      </div>
      {% else %}
      <div class="jumbotron p-3">
        <h2 class="well text-center"><b>ALL PRODUCTS</b></h2>
      </div>
      {% endif %}
      <div class="row">
        {% if brand %}
        {% for b in brand %}
        <div class="col-md-3 mt-3">
            <div class="card">
                {% if b.image == 'None' %}
                  <td><img class="card-img-top" src="{{ url_for('static', filename='images/product_images/default-product-image.png')}}" height="200" alt="{{ b.name }}"></td>
                {% else %}
                  <td><img class="card-img-top" src="{{ url_for('static', filename='images/product_images/' + b.image)}}" height="200" alt="{{ b.name }}"></td>
                {% endif %}
                <div class="card-body">
                    {% if b.discount > 0 %}
                        <p style="text-shadow: 1px 1px 2px black; color: red; transform: rotate(-15deg); position: absolute; top: 20%; left: 20%;"> Discount: {{ b.discount }} % </p>
                    {% endif %}
                    <h5 class="text-center">{{ b.name }}</h5>
                    <p class="text-center">Price: ₱ {{ b.price }}</p>
                </div>
                <div class="card-footer">
                    <a href="/getdesc/{{ b.id }}"class="float-left btn btn-sm btn-primary">Details</a>
                    <form action="{{ url_for('views.addCart')}}" method="POST">
                      {{ csrf_token }}
                        <input type="hidden" name="product_id" value="{{ b.id }}">
                        <button type="submit" class="float-right btn btn-sm btn-warning">Add to Cart</button>
                        <input type="hidden" name="quantity" id="" value="1" min="1" max="{{ b.stock }}">
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}

        {% elif get_catprod %}
        {% for gcp in get_catprod %}
        <div class="col-md-3 mt-3">
            <div class="card">
                {% if gcp.image == 'None' %}
                  <td><img class="card-img-top" src="{{ url_for('static', filename='images/product_images/default-product-image.png')}}" height="200" alt="{{ gcp.name }}"></td>
                {% else %}
                  <td><img class="card-img-top" src="{{ url_for('static', filename='images/product_images/' + gcp.image)}}" height="200" alt="{{ gcp.name }}"></td>
                {% endif %}
                <div class="card-body">
                    {% if gcp.discount > 0 %}
                        <p style="text-shadow: 1px 1px 2px black; color: red; transform: rotate(-15deg); position: absolute; top: 20%; left: 20%;"> Discount: {{ gcp.discount }} % </p>
                    {% endif %}
                    <h5 class="text-center">{{ gcp.name }}</h5>
                    <p class="text-center">Price: ₱ {{ gcp.price }}</p>
                </div>
                <div class="card-footer">
                    <a href="/getdesc/{{ gcp.id }}" class="float-left btn btn-sm btn-primary">Details</a>
                    <form action="{{ url_for('views.addCart')}}" method="POST">
                      {{ csrf_token }}
                        <input type="hidden" name="product_id" value="{{ gcp.id }}">
                        <button type="submit" class="float-right btn btn-sm btn-warning">Add to Cart</button>
                        <input type="hidden" name="quantity" id="" value="1" min="1" max="{{ gcp.stock }}">
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}

        {% else %}
        {% for product in products %}
        <div class="col-md-3 mt-3">
            <div class="card">
                {% if product.image == 'None' %}
                  <td><img class="card-img-top" src="{{ url_for('static', filename='images/product_images/default-product-image.png')}}" height="200" alt="{{ product.name }}"></td>
                {% else %}
                  <td><img class="card-img-top" src="{{ url_for('static', filename='images/product_images/' + product.image)}}" height="200" alt="{{ product.name }}"></td>
                {% endif %}
                <div class="card-body">
                    {% if product.discount > 0 %}
                        <h4 style="text-shadow: 1px 1px 2px black; color: red; transform: rotate(-15deg); position: absolute; top: 20%; left: 18%;"> Discount: {{ product.discount }} % </h4>
                    {% endif %}
                    <h5 class="text-center">{{ product.name }}</h5>
                    <p class="text-center">Price: ₱ {{ product.price }}</p>
                </div>
                <div class="card-footer">
                    <a href="/getdesc/{{ product.id }}" class="float-left btn btn-sm btn-primary">Details</a>
                    <form action="{{ url_for('views.addCart')}}" method="POST">
                      {{ csrf_token }}
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        <button type="submit" class="float-right btn btn-sm btn-warning">Add to Cart</button>
                        <input type="hidden" name="quantity" id="" value="1" min="1" max="{{ product.stock }}">
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}

        {% endif %}
      </div>
    </div>

    <div class="jumbotron p-1 mt-5">
        <h4 class="well text-center">© 2022 Copyright: Sparkle Online Shop - <a href="https://www.facebook.com/profile.php?id=100089051707212&mibextid=ZbWKwL">Team Alola</a></h4>
      </div>
      
  
{% endblock %}

website/templates/customers/order.html
{% extends "base.html" %} 
{% block title %}Home - Sparkle Online Shop{% endblock %} {% block content %}
    <div class="container">
      <div class="jumbotron p-3 well text-center">
        <h1><img src="{{ url_for('static', filename='images/logos/sparkle.png') }}" id="img" x="0" y="0" height="110px" width="110px" style="border:3px solid; border-color:yellow; border-radius:55px" alt="Sparkle Logo"><br>SPARKLE ONLINE SHOP</h1>
      </div>
      <div class="jumbotron p-3">
        <h2 class="well text-center"><b>Your Order</b></h2>
      </div>
      <div class="row bg-light">
        <div class="card ml-sm-3 mt-3 mb-3">
            <h6>
                Invoice: {{ orders.invoice }} <br>
                Status: {{ orders.status }} <br>
                Customer Name: {{ customer.name }} <br>
                Customer Email: {{ customer.email }} <br>
                {% set customer = customer.contact %}
                <div class="card-footer">
                    SHIPPING DETAILS <br>
                    Recipient Name: {{ customer.recipient_name }} <br>
                    Phone Number: +(63){{ customer.phone_number }} <br>
                    Address: {{ customer.address_macro }}, {{ customer.address_micro }} <br>
                    Postal Code: {{ customer.postal_code }}
                </div>
                
            </h6>
        </div>
        <table class="table table-sm">
            <thead align="center">
                <th>Sr</th>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Discount</th>
                <th>Subtotal</th>
            </thead>
            <tbody   align="center">
                {% for key , product in orders.orders.items() %}
                {% set discount = "%.2f" |format((product.discount/100) * product.price|float) %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ product.name }}</td>
                    <td>₱ {{ product.price }}</td>
                    <td>{{ product.quantity }}</td>
                    {% if product.discount > 0 %}
                        <td>{{ product.discount }} % is ₱ {{ discount }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    {% set subTotal = product.quantity|int * product.price|float - discount|float %}
                    <td>₱ {{ subTotal }}</td>
                </tr>

                
                {% endfor %}
            </tbody>
            <table class="table table-sn">
                <tr>
                    <td class="float-left ml-sm-5"><h4><b>Tax : ₱ {{ tax }}</b></h4></td>
                    <td><h4><b>Grand Total : ₱ {{ grandTotal }}</b></h4></td>
                    <td>
                        {% if orders.status == 'Paid' %}
                        {% else %}
                            <form action="/charge" method="POST">
                                {{ csrf_token }}
                                {% set amount = usd_amount.replace('.','') %}
                                <input type="hidden" name="amount" value="{{ amount }}">
                                <input type="hidden" name="invoice" value="{{ orders.invoice }}">                      
                                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                        data-key="{{ key }}"
                                        data-description="Sparkle Shop"
                                        data-amount={{ amount }}
                                        data-locale="auto"></script>
                            </form>
                          {% endif %}
                    </td>
                </tr>
            </table>
        </table>
      </div>

    </div>

    <div class="jumbotron p-1 mt-5">
        <h4 class="well text-center">© 2022 Copyright: Sparkle Online Shop - <a href="https://www.facebook.com/profile.php?id=100089051707212&mibextid=ZbWKwL">Team Alola</a></h4>
    </div>
  

{% endblock %}

website/templates/customers/prodesc.html
{% extends "base.html" %} 
{% block title %}Home - Sparkle Online Shop{% endblock %} {% block content %}
    <div class="container">
      <div class="jumbotron p-3 well text-center">
        <h1><img src="{{ url_for('static', filename='images/logos/sparkle.png') }}" id="img" x="0" y="0" height="110px" width="110px" style="border:3px solid; border-color:yellow; border-radius:55px" alt="Sparkle Logo"><br>SPARKLE ONLINE SHOP</h1>
      </div>
      <div class="jumbotron p-2">
        <h2 class="well text-center"><b>PRODUCT DETAILS</b></h2>
      </div>
      <div class="container mt-3">
        <div class="row" style="align-items: center;">
            <div class="col-md-4 mt-3" id="b_image">
                <div class="jumbotron p-2">
                {% if product.image == 'None' %}
                  <td><img class="card-img-top" src="{{ url_for('static', filename='images/product_images/default-product-image.png')}}" height="400" alt="{{ product.name }}"></td>
                {% else %}
                  <td><img class="card-img-top" src="{{ url_for('static', filename='images/product_images/' + product.image)}}" height="400" alt="{{ product.name }}"></td>
                {% endif %}
                </div>
            </div>
            <div class="col-md-8 mt-3" id="b_image">
                <div class="jumbotron p-2">
                    <h4>Product Name: {{ product.name }}</h4><hr>
                    <p>Product Price: ₱ {{ product.price }}</p><hr>
                    {% if product.discount > 0 %}
                    <p>Product Discount: {{ product.discount }} %</p><hr>
                    {% endif %}
                    <b>Product Description:</b>
                    <p>{{ product.description }}</p><hr>
                    <form action="{{ url_for('views.addCart')}}" method="POST">
                      {{ csrf_token }}
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        <button type="submit" class="btn btn-sm btn-warning mr-sm-3">Add to Cart</button>
                        <label for="">Quantity: </label>
                        <input type="number" name="quantity" id="" value="1" min="1" max="{{ product.stock }}">
                    </form>
                </div>
            </div>
        </div>
      </div>

      <div class="jumbotron p-1 mt-5">
        <h4 class="well text-center">© 2022 Copyright: Sparkle Online Shop - <a href="https://www.facebook.com/profile.php?id=100089051707212&mibextid=ZbWKwL">Team Alola</a></h4>
      </div>
      
  
{% endblock %}

website/templates/customers/result.html
{% extends "base.html" %} 
{% block title %}Home - Sparkle Online Shop{% endblock %} {% block content %}
    <div class="container">
      <div class="jumbotron p-3 well text-center">
        <h1><img src="{{ url_for('static', filename='images/logos/sparkle.png') }}" id="img" x="0" y="0" height="110px" width="110px" style="border:3px solid; border-color:yellow; border-radius:55px" alt="Sparkle Logo"><br>SPARKLE ONLINE SHOP</h1>
      </div>
      <div class="jumbotron p-3">
        <h2 class="well text-center"><b>SEARCH RESULT</b></h2>
      </div>
      <div class="row">
        {% for product in products %}
        <div class="col-md-3 mt-3">
            <div class="card">
                {% if product.image == 'None' %}
                  <td><img class="card-img-top" src="{{ url_for('static', filename='images/product_images/default-product-image.png')}}" height="200" alt="{{ product.name }}"></td>
                {% else %}
                  <td><img class="card-img-top" src="{{ url_for('static', filename='images/product_images/' + product.image)}}" height="200" alt="{{ product.name }}"></td>
                {% endif %}
                <div class="card-body">
                    {% if product.discount > 0 %}
                        <h4 style="text-shadow: 1px 1px 2px black; color: red; transform: rotate(-15deg); position: absolute; top: 20%; left: 18%;"> Discount: {{ product.discount }} % </h4>
                    {% endif %}
                    <h5 class="text-center">{{ product.name }}</h5>
                    <p class="text-center">Price: ₱ {{ product.price }}</p>
                </div>
                <div class="card-footer">
                    <a href="/getdesc/{{ product.id }}" class="float-left btn btn-sm btn-primary">Details</a>
                    <form action="{{ url_for('views.addCart')}}" method="POST">
                      {{ csrf_token }}
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        <button type="submit" class="float-right btn btn-sm btn-warning">Add to Cart</button>
                        <input type="hidden" name="quantity" id="" value="1" min="1" max="{{ product.stock }}">
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
        </div>

    <div class="jumbotron p-1 mt-5">
        <h4 class="well text-center">© 2022 Copyright: Sparkle Online Shop - <a href="https://www.facebook.com/profile.php?id=100089051707212&mibextid=ZbWKwL">Team Alola</a></h4>
    </div>
      
  
{% endblock %}

website/templates/customers/thanks.html
<h1 text-align="center">Thank you for shopping with us!</h1>