website/auth.py
import functools
from flask import Flask, Blueprint, render_template, request, flash, redirect, url_for, g, session, jsonify
from .users.models import User, Contact, CustomerOrder
from .products.models import Product, Category, Brand
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, search
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.utils import secure_filename
import uuid as uuid
import os, secrets
from sqlalchemy.sql import func
import stripe


stripe_keys = {
  'secret_key': 'sk_test_51LwefbJaasrIB7O4tvbZvw1841Q9yoUKxEmykSaKLqYPJPDoQOaCLLAh0iJrJmplm6NjOwSIIYW9Al8acQ996WDo00NAccCHbP',
  'publishable_key': 'pk_test_51LwefbJaasrIB7O42NsLYWLlOa2gGvM7ehDeTqicqbKoRq2EfYOEo0a42AU4kcITbcshI8RQj2HgZQ7x0w77dkoB00veLeVIYD'
}

stripe.api_key = stripe_keys['secret_key']

UPLOAD_FOLDER = 'website/static/images/profile_images'
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

auth = Blueprint('auth', __name__)

def brands():
    brands = Brand.query.filter(Brand.id==Product.brand_id)
    return brands


def categories():
    categories = Category.query.filter(Category.id==Product.category_id)
    return categories



@auth.route('/logreg', methods=['GET', 'POST'])
def logreg():
    if current_user.is_authenticated:
        if current_user.id == 1:
            flash("You are still logged in Admin", category="error")
            return redirect(url_for('auth.adminhome'))
        if current_user.id >= 2:
            flash("You are still logged in User", category="error")
            return redirect(url_for('auth.home'))
    else:
        return render_template("logregtemp.html")


@auth.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if current_user.is_authenticated:
        if current_user.id >= 2:
            prods = Product.query.filter(Product.stock>0)
            users = User.query.all()

            return render_template("customers/index.html", user=current_user, users=users, products=prods, categories=categories(), brands=brands())

        else:
            flash("Dear Admin, please refrain from doing unwanted behaviour. Gracias!", category="error")
            return redirect(url_for('auth.adminhome'))
    else:
        return redirect(url_for('auth.login'))


@auth.route('/result')
@login_required
def result():
    if current_user.is_authenticated:
        if current_user.id >= 2:
            searchword = request.args.get('q')
            products = Product.query.msearch(searchword, fields=['name', 'description'], limit=4)
            return render_template("customers/result.html", user=current_user, products=products, brands=brands(), categories=categories())
        
        else:
            flash("Dear Admin, please refrain from doing unwanted behaviour. Gracias!", category="error")
            return redirect(url_for('auth.adminhome'))
    else:
        return redirect(url_for('auth.login'))



@auth.route('/adminhome', methods=['GET', 'POST'])
@login_required
def adminhome():
    if current_user.is_authenticated:
        if current_user.id == 1:
            products = Product.query.all()
            brands = Brand.query.all()
            categories = Category.query.all()
            users = User.query.all()
            
            return render_template("admin/panelproducts.html", user=current_user, users=users, products=products, categories=categories, brands=brands)
        else:
            flash("You do not have admin privilege to access this page", category="error")
            return redirect(url_for('auth.home'))
    else:
        return redirect(url_for('auth.login'))


@auth.route('/getdesc/<int:id>', methods=['GET', 'POST'])
@login_required
def getDesc(id):
    if current_user.is_authenticated:
        if current_user.id >= 2:
            product = Product.query.get_or_404(id)
            users = User.query.all()
            
            return render_template("customers/prodesc.html", user=current_user, users=users, product=product)
        else:
            flash("Dear Admin, please refrain from doing unwanted behaviour. Gracias!", category="error")
            return redirect(url_for('auth.adminhome'))
    else:
        return redirect(url_for('auth.login'))


@auth.route('/brands', methods=['GET', 'POST'])
@login_required
def panelBrand():
    if current_user.is_authenticated:
        if current_user.id == 1:
            products = Product.query.all()
            categories = Category.query.all()
            brands = Brand.query.all()
            users = User.query.all()
            
            return render_template("admin/panelbrands.html", user=current_user, users=users, products=products, categories=categories, brands=brands)
        else:
            flash("You do not have admin privilege to access this page", category="error")
            return redirect(url_for('auth.home'))
    else:
        return redirect(url_for('auth.login'))

 
 
@auth.route('/getbrand/<int:id>', methods=['GET', 'POST'])
@login_required
def getBrand(id):
    if current_user.is_authenticated:
        if current_user.id >= 2:
            brand = Product.query.filter_by(brand_id=id)
            users = User.query.all()
            
            return render_template("customers/index.html", user=current_user, users=users, brands=brands(), brand=brand, categories=categories())
        else:
            flash("Dear Admin, please refrain from doing unwanted behaviour. Gracias!", category="error")
            return redirect(url_for('auth.adminhome'))
    else:
        return redirect(url_for('auth.login'))


@auth.route('/getcategory/<int:id>', methods=['GET', 'POST'])
@login_required
def getCategory(id):
    if current_user.is_authenticated:
        if current_user.id >= 2:
            get_catprod = Product.query.filter_by(category_id=id)
            users = User.query.all()
            
            return render_template("customers/index.html", user=current_user, users=users, categories=categories(), get_catprod=get_catprod, brands=brands())
        else:
            flash("Dear Admin, please refrain from doing unwanted behaviour. Gracias!", category="error")
            return redirect(url_for('auth.adminhome'))
    else:
        return redirect(url_for('auth.login'))

@auth.route('/categories', methods=['GET', 'POST'])
@login_required
def panelCat():
    if current_user.is_authenticated:
        if current_user.id == 1:
            products = Product.query.all()
            brands = Brand.query.all()
            categories = Category.query.all()
            users = User.query.all()

            return render_template("admin/panelcategories.html", user=current_user, users=users, products=products, categories=categories, brands=brands)
        
        else:
            flash("You do not have admin privilege to access this page", category="error")
            return redirect(url_for('auth.home'))
    else:
        return redirect(url_for('auth.login'))

@auth.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    users = User.query.all()
    contact = Contact.query.all()   
    if current_user.id == 1:
        return render_template("admin/profile.html", user=current_user, users=users)
    if current_user.id >= 2:
        return render_template("customers/profile.html", user=current_user, users=users, categories=categories(), brands=brands(), contact=contact)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                if user.id == 1:
                    flash(f'Welcome Admin { user.name }, you have logged in successfully!', category='success')
                    login_user(user, remember=True)
                    session['id'] = current_user.id
                    return redirect(url_for('auth.adminhome'))
                if user.id >= 2:
                    flash(f'Welcome { user.name }, you have logged in successfully!', category='success')
                    login_user(user, remember=True)
                    session['id'] = current_user.id
                    return redirect(url_for('auth.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return redirect(url_for('auth.logreg', user=current_user))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    session['id'] = None
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        profile_image = request.files['image1']
        # if user does not select file, return to signup
        if profile_image.filename == '':
            profile_image = 'None'
        elif profile_image and not allowed_file(profile_image.filename):
            flash('Please select an image file', category="error")
            return redirect(url_for('auth.sign_up'))
        elif profile_image and allowed_file(profile_image.filename):
            # Grab Image Name
            pic_filename = secure_filename(profile_image.filename)
            # Set UUID
            pic_name = str(uuid.uuid1()) + "_" + pic_filename
            # Save that Image
            profile_image.save(os.path.join(app.config['UPLOAD_FOLDER'], pic_name))
            # Change it to string to save to db
            profile_image = pic_name

        user = User.query.filter_by(email=email).first()
        if user:

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/homestyle.css') }}" />
    <!-- CSS only -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/font-awesome.min.css') }}" />

    <title>{% block title %}Home{% endblock %}</title>
    <style>
      body{
        padding-top: 70px !important;
      }
    </style>
  
</head>
<body>
  {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            <a class="nav-item nav-link mr-sm-5" id="logo" href="#" style="color: white"><img src="{{ url_for('static', filename='images/logos/sparkle.png') }}" id="img" x="0" y="0" height="30px" width="30px" style="border:1px solid; border-color:yellow; border-radius:15px" alt="Sparkle Logo"></a>
              {% if user.id == 1 %}
                <a class="nav-item nav-link" id="profile" href="/profile" style="color: white">Profile</a>
                <li class="nav-item nav-link dropdown">
                  <a href="#" class="dropdown-toggle" style="text-decoration: none; color: white" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin Panel<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="nav-item nav-link" id="adminhome" href="/adminhome" style="text-align: center; color:black;"><b>Products</b></a>
                    </li>
                    <li>
                      <a class="nav-item nav-link" id="brands" href="/brands" style="text-align: center; color:black;"><b>Brands</b></a>
                    </li>
                    <li>
                      <a class="nav-item nav-link" id="categories" href="/categories" style="text-align: center; color:black;"><b>Categories</b></a>
                    </li>
                  </ul>
                </li>
              {% else %}
                <form class="form-inline my-2 my-lg-0 collapse navbar-collapse navbar-right" id="navbar-collapse" action="{{ url_for('auth.result') }}">
                  {{ csrf_token }}
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
                  <button class="btn btn-outline-success mr-sm-5" type="submit">Search</button>
                </form>
                <a class="nav-item nav-link" id="cart" href="{{ url_for('auth.getCart') }}" style="color: white"><button class="btn btn-sm btn-secondary"><img src="{{ url_for('static', filename='images/icons/cart.jpg') }}" id="img" x="0" y="0" height="30px" width="30px" style="border:1px solid; border-color:yellow; border-radius:15px" alt="Cart"> {{session['shopcart']|length}} item/s</button></a>
                <a class="nav-item nav-link active" id="profile" href="/profile" style="color: white">Profile</a>
                <a class="nav-item nav-link" id="index" href="/" style="color: white">All Products</a>
                <li class="nav-item nav-link dropdown">
                  <a href="#" class="dropdown-toggle" style="text-decoration: none; color: white" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    {% for brand in brands %}
                      <a class="nav-item nav-link" id="brand" href="/getbrand/{{ brand.id }}" style="text-align: center; color:black;"><b>{{ brand.name }}</b></a>
                    {% endfor %}
                  </ul>
                </li>
                <li class="nav-item nav-link dropdown">
                  <a href="#" class="dropdown-toggle" style="text-decoration: none; color: white" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    {% for category in categories %}
                      <a class="nav-item nav-link" id="category" href="/getcategory/{{ category.id }}" style="text-align: center; color:black;"><b>{{ category.name }}</b></a>
                    {% endfor %}
                  </ul>
                </li>
              {% endif %}
              <li class="nav-item nav-link dropdown">
                <a href="#" class="dropdown-toggle" style="text-decoration: none; color: white" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  {% if current_user.profile_image == 'None' %}
                  <td><img src="{{ url_for('static', filename='images/profile_images/default-profile-image.png')}}" x="0" y="0" height="30px" width="30px" style="border:1px solid; border-color:black; border-radius:15px" alt="{{ current_user.name }}"></td>
                  {% else %}
                  <td><img src="{{ url_for('static', filename='images/profile_images/' + current_user.profile_image)}}" x="0" y="0" height="30px" width="30px" style="border:1px solid; border-color:black; border-radius:15px" alt="{{ current_user.name }}"></td>
                  {% endif %}
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <a class="nav-item nav-link" id="logout" href="/logout" style="text-align: center; color:black;" onclick="return confirm('Are you sure you want to logout your account?')"><b>Logout</b></a>
                </ul>
              </li>
          </div>
        </div>
      </nav>
    {% endif %}
  
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %} {% if category ==
      'error' %}
      <div class="alert alert-danger alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}
      <div class="alert alert-success alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %}
  
      <div class="container">{% block content %} {% endblock %}</div>
      <script src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</body>
</html>

website/templates/logregtemp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login/Signup</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/logregstyle.css') }}" />
</head>
<body>
  <div class="folder">
  {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
      {{ message }}
      <span type="button" class="btn-close float-right" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </span>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
      {{ message }}
      <span type="button" class="btn-close float-right" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </span>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">
        <div class="cardintro">
          <div class="intro-box">
            <div class="card-1">
              <div>
                <div><img src="{{ url_for('static', filename='images/logos/sparkle.png') }}" id="img" x="0" y="0" height="150px" width="150px" style="border:5px solid; border-color:yellow; border-radius:75px" alt="Sparkle Logo"></div><br>
                <h4>Welcome to <u>Sparkle Online Shop</u>. A flask-based online shopping platform that enables users,
                or customers, to look for different products, offers, and online purchases. The project
                comprises of a list of products that are offered and are shown in different product categories.
                These products can be browsed by the user based on categories. The consumer has the option of
                adding a product to their shopping basket if they like it. When a person wants to check out, he
                must first register on the website. Next time, he can log in using the same ID and password. Now,
                he has the option of paying with a credit card, gcash, or cash upon delivery. Following a successful
                transaction, the user receives a copy of the shopping receipt on his email address. The complete
                system is made here using the Flask and Jinja frameworks.</h4>
              </div>
            </div>
          </div>
        </div>
        <div class="card">
            <div class="inner-box" id="card">
                <div class="card-front">
                    <form action="{{ url_for('auth.login') }}" method="POST">
                      {{ csrf_token }}
                        <h2 align="center">Login</h2>
                        <div class="form-group">
                          <label for="email">Email Address</label>
                          <input
                            type="email"
                            class="form-control"
                            id="email"
                            name="email"
                            placeholder="Enter email"
                          />
                        </div><br>
                        <div class="form-group">
                          <label for="password">Password</label>
                          <input
                            type="password"
                            class="form-control"
                            id="password"
                            name="password"
                            placeholder="Enter password"
                          />
                        </div>
                        <br />
                        <button type="submit" class="submit-btn">Submit</button>
                        <input type="checkbox"><span>Remember Me</span>
                      </form>
                      <button type="button" class="btn" onclick="openSignup()">I'm New Here</button>
                </div>
                <div class="card-back">
                    <form action="{{ url_for('auth.sign_up') }}" method="POST" enctype="multipart/form-data">
                      {{ csrf_token }}
                        <h2 align="center">Sign Up</h2>
                        <div class="form-group">
                          <input
                            type="email"
                            class="form-control"
                            id="email"
                            name="email"
                            placeholder="Enter email"
                          />
                        </div>
                        <div class="form-group">
                          <input
                            type="text"
                            class="form-control"
                            id="name"
                            name="name"
                            placeholder="Enter your name"
                          />
                        </div>
                        <label for="profile_image"><h6><i>Upload your profile photo (Optional)</i></h6></label>
                        <div class="form-group">
                          <input
                            type="file"
                            style="padding: 4px"
                            class="form-control"
                            id="image1"
                            name="image1"
                          />
                        </div>
                        <div class="form-group">
                          <input
                            type="password"
                            class="form-control"
                            id="password1"
                            name="password1"
                            placeholder="Enter password"
                          />
                        </div>
                        <div class="form-group">
                          <input
                            type="password"
                            class="form-control"
                            id="password2"
                            name="password2"
                            placeholder="Confirm password"
                          />
                        </div>
                        <br />
                        <button type="submit" class="submit-btn" style="margin-top: 10px">Submit</button>
                        <input type="checkbox"><span>Remember Me</span>
                      </form>
                      <button type="button" class="btn" onclick="openLogin()" style="margin-top: 35px">I have an account</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        var card = document.getElementById("card");

        function openSignup(){
            card.style.transform = "rotateY(-180deg)";
        }
        function openLogin(){
            card.style.transform = "rotateY(0deg)";
        }
    </script>
    <script src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/a076d05399.js') }}"></script>
</body>
</html>